services:

    Garamszegi\Bundle\TaskManagerBundle\Command\ExecuteCommand:
        arguments:            
            - "%garamszegi_command_task_manager.log_path%"
        tags: [console.command]

    